os: linux
dist: bionic
language: python
python: 3.6


install:
  - pip install poetry

script:
  - poetry update
  - poetry run invoke build


deploy:
  edge: true
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  repo: P403n1x87/P403n1x87.github.io
  target_branch: master
  local_dir: output
  on:
    branch: master
