# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title           : The Hub of Heliopolis
author          : Gabriele N. Tornetta
email           : phoenix1987@gmail.com
start-year      : 2017
baseurl         : ""                             # the subpath of your site, e.g. /blog
url             : "https://p403n1x87.github.io/" # the base hostname & protocol for your site
github_username :  P403n1x87

description: >
  The Hub of Heliopolis is the <i>tech bay</i> of <a href="http://thenestofheliopolis.blogspot.co.uk/">The Nest of Heliopolis</a>.
  It is the home of all my <i>encounters</i> with technology that I consider worth
  sharing with the World.

# Build settings
markdown : kramdown
exclude  : [build, serve, vendor, Gemfile*]

gems:
  - jekyll-toc
