# This file is part of "the-hub-of-heliopolis" which is released under GPL.
#
# See file LICENCE or go to http://www.gnu.org/licenses/ for full license
# details.
#
# the-hub-of-heliopolis is a Python wrapper around Austin, the CPython frame stack
# sampler.
#
# Copyright (c) 2018-2020 Gabriele N. Tornetta <phoenix1987@gmail.com>.
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[tool.poetry]
authors = ["Gabriele N. Tornetta <phoenix1987@gmail.com>"]
classifiers = []
description = ""
documentation = "https://the-hub-of-heliopolis.readthedocs.io"
homepage = "https://github.com/P403n1x87/the-hub-of-heliopolis"
keywords = []
license = "GPL-3.0-or-later"
name = "the-hub-of-heliopolis"
package-mode = false
readme = "README.md"
repository = "https://github.com/P403n1x87/the-hub-of-heliopolis"
version = "0.1.0"

[tool.poetry.dependencies]
invoke = "^3.0"
pelican = {extras = ["markdown"], version = "^4.12"}
pygments = "^2.6"
python = ">=3.12"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
