name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install and Build 🔧
        run: |
          pip install poetry
          poetry update
          poetry run invoke build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: output
          repository-name: P403n1x87/P403n1x87.github.io
          token: ${{ secrets.GH_PAGES_TOKEN }}
